<?php
// auto-generated by sfPropelCrud
// date: 2014/05/27 06:29:45
?>
<?php use_helper('Object') ?>

<?php echo form_tag('report/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($report, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Image:</th>
  <td><?php echo input_file_tag('file') ?></td>
</tr>
<tr>
  <th>Year:</th>
  <td><?php echo object_input_tag($report, 'getYear', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Host country:</th>
  <td><?php echo object_input_tag($report, 'getHostCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($report, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Reportfile:</th>
  <td><?php echo input_file_tag('reportfile') ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($report->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'report/delete?id='.$report->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'report/show?id='.$report->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'report/list') ?>
<?php endif; ?>
</form>
