<?php
// auto-generated by sfPropelCrud
// date: 2014/05/27 06:29:45
?>
<h1>report</h1>

<table>
<thead>
<tr>
  <th>Image</th>
  <th>Year</th>
  <th>Host country</th>
  <th>Body</th>
  <th>Reportfile</th>
  <th>Id</th>
</tr>
</thead>
<tbody>
<?php foreach ($reports as $report): ?>
<tr>
    <td><?php echo $report->getImage() ?></td>
      <td><?php echo $report->getYear() ?></td>
      <td><?php echo $report->getHostCountry() ?></td>
      <td><?php echo $report->getBody() ?></td>
      <td><?php echo $report->getReportfile() ?></td>
      <td><?php echo link_to($report->getId(), 'report/show?id='.$report->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'report/create') ?>
