<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/27 07:45:33

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:root@localhost/gn_sns',
  'encode' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
