<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/27 07:58:32
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
