default:
  has_layout: on

  # javascripts:    [jquery-1.10.2.min.js, bootstrap/bootstrap.min.js, plugins/jquery.bxslider.min.js, plugins/jquery.centralized.min.js, plugins/jquery.fixedonlater.min.js, plugins/jquery.hashloader.min.js, plugins/jquery.mixitup.min.js, plugins/jquery.nav.min.js, plugins/jquery.parallax-1.1.3.min.js, plugins/jquery.responsivevideos.min.js, plugins/jquery.scrollTo.min.js, plugins/jquery.tweet.min.js, plugins/jquery.tweetCarousel.min.js, application/application.min.js]


  stylesheets: [main, mypage]