default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main]

  javascripts:    [jquery-1.10.2.min, bootstrap/bootstrap.min, plugins/jquery.bxslider.min, plugins/jquery.centralized.min, plugins/jquery.fixedonlater.min, plugins/jquery.hashloader.min, plugins/jquery.mixitup.min, plugins/jquery.nav.min, plugins/jquery.parallax-1.1.3.min, plugins/jquery.responsivevideos.min, plugins/jquery.scrollTo.min, plugins/jquery.tweet.min, plugins/jquery.tweetCarousel.min, application/application.min]

  has_layout:     on
  layout:         layout
