<?php
// auto-generated by sfPropelCrud
// date: 2014/05/27 06:29:45
?>
<?php

/**
 * report actions.
 *
 * @package    gn_sns
 * @subpackage report
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class reportActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('report', 'list');
  }

  public function executeList()
  {
    $this->reports = ReportPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->report = ReportPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->report);
  }

  public function executeCreate()
  {
    $this->report = new Report();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->report = ReportPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->report);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $report = new Report();
    }
    else
    {
      $report = ReportPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($report);
    }
    //report用の写真をアップロードディレクトリに格納
    $reportimagefileName = $this->getRequest()->getFileName('file');
    $this->getRequest()->moveFile('file', sfConfig::get('sf_upload_dir').'/'.$reportimagefileName);
    //報告書をアップロードディレクトリに格納
    $reporttextfileName = $this->getRequest()->getFileName('reportfile');
    $this->getRequest()->moveFile('reportfile', sfConfig::get('sf_upload_dir').'/'.$reporttextfileName);

    $report->setImage($reportimagefileName);
    $report->setYear($this->getRequestParameter('year'));
    $report->setHostCountry($this->getRequestParameter('host_country'));
    $report->setBody($this->getRequestParameter('body'));
    $report->setReportfile($reporttextfileName);
    $report->setId($this->getRequestParameter('id'));

    $report->save();

    return $this->redirect('report/show?id='.$report->getId());
  }

  public function executeDelete()
  {
    $report = ReportPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($report);

    $report->delete();

    return $this->redirect('report/list');
  }
}
