<?php
// auto-generated by sfPropelCrud
// date: 2014/05/27 02:02:23
?>
<h1>friend</h1>

<table>
<thead>
<tr>
  <th>User</th>
  <th>Image</th>
  <th>Body</th>
  <th>Created at</th>
  <th>Updated at</th>
  <th>Id</th>
</tr>
</thead>
<tbody>
<?php foreach ($friends as $friend): ?>
<tr>
      <td><?php echo $friend->getUserId() ?></td>
      <td><?php echo $friend->getImage() ?></td>
      <td><?php echo $friend->getBody() ?></td>
      <td><?php echo $friend->getCreatedAt() ?></td>
      <td><?php echo $friend->getUpdatedAt() ?></td>
      <td><?php echo link_to($friend->getId(), 'friend/show?id='.$friend->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'friend/create') ?>
