<?php
// auto-generated by sfPropelCrud
// date: 2014/08/17 22:12:27
?>
<?php use_helper('Object') ?>


<?php echo form_tag('post/update', 'multipart=true') ?>

<?php echo object_input_hidden_tag($post, 'getId') ?>

<table>
<tbody>
<tr>
  <!-- ここはsubscriber idを取ってhidden tagで送る -->
  <!-- <th>User:</th> -->
  <!-- <td> -->
    <?php //echo object_select_tag($post, 'getUserId', array ('related_class' => 'User','include_blank' => true,)) ?>
<!-- </td> -->
<!-- </tr> -->
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($post, 'getTitle', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <!-- ファイルアップロード -->

  <th>Image:</th>
  <td>
  <?php echo input_file_tag('file') ?>
</td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($post, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <!-- selectタグにする。カテゴリそれぞれに対して数字を割り当てる。 -->
  <th>Category:</th>
  <td>
<?php echo select_tag('category', options_for_select(array(
  '1'  => 'POLITICS',
  '2'    => 'ECONOMICS',
  '3' => 'INTERNATIONAL',
  '4'    => 'BUSSINESS',
  '5'   => 'ENTERTAINMENT'))) ?>
</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($post->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'post/delete?id='.$post->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'post/show?id='.$post->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'post/list') ?>
<?php endif; ?>
</form>
