<?php
// auto-generated by sfPropelCrud
// date: 2014/05/25 19:26:44
?>
<h1>blog</h1>
<table>
<thead>
<tr>

  <th>User</th>
  <th>Title</th>
  <th>Image</th>
  <th>Body</th>
  <th>Created at</th>
  <th>Updated at</th>
  <th>Id</th>
</tr>
</thead>
<tbody>
<?php foreach ($blogs as $blog): ?>
<tr>

    <td><?php echo $blog->getUserId() ?></td>
      <td><?php echo $blog->getTitle() ?></td>
      <td><?php echo $blog->getImage() ?></td>
      <td><?php echo $blog->getBody() ?></td>
      <td><?php echo $blog->getCreatedAt() ?></td>
      <td><?php echo $blog->getUpdatedAt() ?></td>
      <td><?php echo link_to($blog->getId(), 'blog/show?id='.$blog->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<div align="right">
<?php echo form_tag('blog/create') ?>
<?php echo input_hidden_tag('oya_id', $blog->getId()) ?>
<?php echo input_hidden_tag('oya_title', $blog->getTitle()) ?>
<?php echo input_hidden_tag('oya_body', $blog->getBody()) ?>
<?php echo submit_tag('返信') ?>
</form>
</div>

<?php echo link_to ('create', 'blog/create') ?>
