<?php
// auto-generated by sfPropelCrud
// date: 2014/05/25 19:26:44
?>
<table>
<tbody>
<tr>
<th>User: </th>
<td><?php echo $blog->getUserId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $blog->getTitle() ?></td>
</tr>
<tr>
<th>Image: </th>
<td><?php echo $blog->getImage() ?></td>
</tr>
<tr>
<th>Body: </th>
<td><?php echo $blog->getBody() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $blog->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $blog->getUpdatedAt() ?></td>
</tr>
<tr>
<th>Id: </th>
<td><?php echo $blog->getId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'blog/edit?id='.$blog->getId()) ?>
&nbsp;<?php echo link_to('list', 'blog/list') ?>
