<?php
// auto-generated by sfPropelCrud
// date: 2014/08/17 22:12:27
?>
<?php use_helper('Object') ?>

<?php echo form_tag('post/update') ?>

<?php echo object_input_hidden_tag($post, 'getId') ?>

<table>
<tbody>
<tr>
  <!-- ここはsubscriber idを取ってhidden tagで送る -->
  <th>User:</th>
  <td><?php echo object_select_tag($post, 'getUserId', array (
  'related_class' => 'User',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($post, 'getTitle', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Image:</th>
  <td><?php echo object_textarea_tag($post, 'getImage', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($post, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Category:</th>
  <td><?php echo object_input_tag($post, 'getCategory', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($post->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'post/delete?id='.$post->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'post/show?id='.$post->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'post/list') ?>
<?php endif; ?>
</form>
